package jp.toastkid.yobidashi.compact.editor

enum class MenuCommand {
    SAVE, CLOSE, PASTE_AS_QUOTATION, FIND, TO_TABLE, UNORDERED_LIST, ORDERED_LIST, TASK_LIST,
    ITALIC, BOLD, STRIKETHROUGH, BLOCKQUOTE, CODE_BLOCK, FONT_COLOR, COUNT, WEB_SEARCH, DICTIONARY_SEARCH,
    TRANSLATION_TO_ENGLISH
}